site:
  title: Play-IoT Documentation
  start_page: playio-vpn-docs::index.adoc
content:
  sources:
  - url: https://github.com/play-iot/iot-vpn.git
    branches: feature/documentation-pages
    start_path: docs
asciidoc:
  attributes:
    page-github-repo: https://github.com/play-iot/iot-vpn
    page-simple-icons-cdn: https://cdn.jsdelivr.net/npm/simple-icons@v6/icons
    page-docsearch-cdn: https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn
    page-lunr-cdn: https://cdn.jsdelivr.net/npm/lunr@2.3.9/lunr.min.js
    page-lunr-lang-cdn: https://cdn.jsdelivr.net/npm/lunr-languages@1.9.0/lunr.stemmer.support.js
antora:
  extensions:
    - '@antora/lunr-extension'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true